                                                                                                                                                                                                                                 "use client";
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                import MovieCard, { Movie } from "./MovieCard";
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                type MovieRowProps = {
                                                                                                                                                                                                                                  title: string;
                                                                                                                                                                                                                                    movies: Movie[];
                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    export default function MovieRow({
                                                                                                                                                                                                                                      title,
                                                                                                                                                                                                                                        movies,
                                                                                                                                                                                                                                        }: MovieRowProps) {
                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <section className="mb-14">
                                                                                                                                                                                                                                                    <div className="mb-5 flex items-center justify-between">
                                                                                                                                                                                                                                                            <h2 className="text-2xl font-light text-white">
                                                                                                                                                                                                                                                                      {title}
                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                      <button className="text-sm text-white/60 transition hover:text-white">
                                                                                                                                                                                                                                                                                                View All
                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                    <div className="flex gap-5 overflow-x-auto pb-4 scrollbar-hide snap-x snap-mandatory">
                                                                                                                                                                                                                                                                                                                            {movies.map((movie) => (
                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                  key={movie.id}
                                                                                                                                                                                                                                                                                                                                                              className="min-w-[190px] snap-start"
                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                    <MovieCard movie={movie} />
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                  }