import Link from "next/link";

import {
  getMovieTrailer,
    getMovieCredits,
      getSimilarMovies,
      } from "@/lib/tmdb";

      import MovieClient from "@/components/movie/MovieClient";
import MovieActions from "@/components/movie/MovieActions";
      import ContinueWatchingTracker from "@/components/continue-watching/ContinueWatchingTracker";
      import WatchlistButton from "@/components/watchlist/WatchlistButton";
      import SimilarMovies from "@/components/movie/SimilarMovies";
import Synopsis from "@/components/movie/Synopsis";
import PageTransition from "@/components/layout/PageTransition";
import { getNavbarVariant } from "@/lib/visual/navbar";

      type Props = {
        params: Promise<{
            id: string;
              }>;
              };

              const API = process.env.NEXT_PUBLIC_TMDB_API_KEY;

              const IMG = "https://image.tmdb.org/t/p/original";
              const POSTER = "https://image.tmdb.org/t/p/w500";

              async function getMovie(id: string) {
                const res = await fetch(
                    `https://api.themoviedb.org/3/movie/${id}?api_key=${API}`,
                        {
                              next: {
                                      revalidate: 3600,
                                            },
                                                }
                                                  );

                                                    if (!res.ok) {
                                                        throw new Error("Failed to load movie.");
                                                          }

                                                            return res.json();
                                                            }

                                                            export default async function MoviePage({
                                                              params,
                                                              }: Props) {
                                                                const { id } = await params;

                                                                  const movie = await getMovie(id);
                                                                    const trailer = await getMovieTrailer(id);
                                                                      const credits = await getMovieCredits(id);
                                                                        const similar = await getSimilarMovies(id);

                                                                          return (
                                                                              <main className="min-h-screen bg-[#050505] text-white">
                                                                                    <ContinueWatchingTracker movie={movie} />

                                                                                          <div className="relative h-[72vh]">

                                                                                                  <img
                                                                                                            src={`${IMG}${movie.backdrop_path}`}
                                                                                                                      alt={movie.title}
                                                                                                                                className="absolute inset-0 h-full w-full object-cover"
                                                                                                                                        />

                                                                                                                                                <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-black/55 to-black/25" />

        <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#050505] to-transparent pointer-events-none" />

                                                                                                                                                        <div className="relative mx-auto flex h-full max-w-7xl items-end justify-between px-6 pb-16">

                                                                                                                                                                  <div>

                                                                                                                                                                              <Link
                                                                                                                                                                                            href="/browse"
                                                                                                                                                                                                          className="mb-8 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-5 py-2.5 text-sm font-medium text-white/90 backdrop-blur-2xl transition-all duration-300 hover:bg-white/20 hover:border-white/30"
                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                    ← Back
                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                            <h1 className="max-w-3xl text-5xl font-extralight leading-[0.95] tracking-tight md:text-7xl">
                                                                                                                                                                                                                                                                          {movie.title}
                                                                                                                                                                                                                                                                                      </h1>

                                                                                                                                                                                                                                                                                                                                        <div className="mt-8 flex flex-wrap items-center gap-3">

                                                                                                                                                                                                                                                                                                                                                      <span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-white/90 backdrop-blur-xl">
                                                                                                                                                                                                                                                                                                                                                                      ★ {movie.vote_average.toFixed(1)}
                                                                                                                                                                                                                                                                                                                                                                                    </span>

                                                                                                                                                                                                                                                                                                                                                                                                  <span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-white/90 backdrop-blur-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                  {(movie.release_date || "").slice(0, 4)}
                                                                                                                                                                                                                                                                                                                                                                                                                                </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-white/90 backdrop-blur-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {movie.runtime} min
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {movie.genres?.slice(0, 2).map((genre: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={genre.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-white/90 backdrop-blur-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {genre.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hidden md:flex items-end pb-2"><WatchlistButton
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          movie={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: movie.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: movie.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    poster: movie.poster_path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? POSTER + movie.poster_path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backdrop: movie.backdrop_path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? IMG + movie.backdrop_path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                year: (movie.release_date || "").slice(0, 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rating: movie.vote_average,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

      <section className="mx-auto max-w-7xl px-6 py-12">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Synopsis text={movie.overview} />

        
<MovieActions
                    tmdbId={movie.id}
          title={movie.title}
        />

<MovieClient
  movieId={movie.id}
  movieTitle={movie.title}
  credits={credits}
/>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SimilarMovies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              movies={similar.results ?? []}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }